dubbo:
  application:
    name: dubbo-springboot-learn-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:192.168.183.139}:2181
server:
  port: 9091
