dubbo:
  application:
    name: dubbo-springboot-learn-consumer
    qos-port: 22223
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:192.168.183.139}:2181

server:
  port: 9090
